sudo: required
services:
  - docker

before_install:
  - docker build -t andy537/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andy537/react-test npm run test

after_success:
  - docker build -t andy537/multi-client ./client
  - docker build -t andy537/multi-nginx ./nginx
  - docker build -t andy537/multi-server ./server
  - docker build -t andy537/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push andy537/multi-client
  - docker push andy537/multi-nginx
  - docker push andy537/multi-server
  - docker push andy537/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-1"
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-us-west-1-541263489771"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
